definitions = {
'racial_identity': ['"Race is a socially constructed system of classifying individuals according to phenotypical characteristics that are genetically determined but not always consistent."', 'http://labs.psychology.illinois.edu/~lyubansk/Conflict/Identity.htm'],	
'mental_health': [""""Mental health includes our emotional, psychological, and social well-being. It affects how we think, feel, and act. It also helps determine how we handle stress, relate to others, and make choices. Mental health is important at every stage of life, from childhood and adolescence through adulthood." """, 'https://www.mentalhealth.gov/basics/what-is-mental-health'],	
'lgbtq_identity': ["""'The acronym LGBT stands for “Lesbian, Gay, Bisexual, and Transgender' """, 'http://www.rainbowwelcome.org/faq#faq1'],	
'feminism': [""""A person who believes in the social, political, and economic equality of the sexes" """, 'https://www.ted.com/talks/chimamanda_ngozi_adichie_we_should_all_be_feminists/transcript?language=en'],	
'cultural_appropriation': ["""'The act of taking or using things from a culture that is not your own, especially without showing that you understand or respect this culture:' """, 'https://dictionary.cambridge.org/dictionary/english/cultural-appropriation'],	
'inclusivity': ["""'The quality of trying to include many different types of people and treat them all fairly and equally' """, 'https://dictionary.cambridge.org/us/dictionary/english/inclusivity'],	
'islamophobia': [""""Islamophobia is when Muslims are the victims of attacks just because of their religion."   """ , 'http://www.bbc.co.uk/newsround/40324678'],	
'socioeconomic_privilege': [""""Socio-economic privilege actually doesn't mean being super rich. It means you could afford things like going to summer camp or playing after-school sports. Socio-economic privilege means being able to afford to go to college, or being able to afford putting yourself in debt in order to go to college. It means being able to afford a full-time, unpaid internship." """, 'https://www.elitedaily.com/life/privilege-benefiting-from-no-idea/1496370'],	
'ableism': [""""The practices and dominant attitudes in society that devalue and limit the potential of persons with disabilities. A set of practices and beliefs that assign inferior value (worth) to people who have developmental, emotional, physical or psychiatric disabilities." """, 'http://www.stopableism.org/p/what-is-ableism.html'],	
'me_too': [""""The #MeToo movement is meant "to help survivors of sexual violence, particularly young women of color from low wealth communities, find pathways to healing. Using the idea of “empowerment through empathy,” the me too. movement was ultimately created to ensure survivors know they're not alone in their journey." """, 'https://metoomvmt.org/'],	
'dating_fetishism': ["""'Fetishizing is when people are attracted to the color of [one's] skin and the racial stereotypes that have been assigned to [people] of [one's] race.  """, 'https://ravishly.com/2015/09/07/problem-racial-fetishization'],	
'allyship': ["""'Allyship is not an identity—it is a lifelong process of building relationships based on trust, consistency, and accountability with marginalized individuals and/or groups of people' """, 'https://theantioppressionnetwork.com/allyship/'],
'gentrification': ["""'Gentrification is a general term for the arrival of wealthier people in an existing urban district, a related increase in rents and property values, and changes in the district's character and culture. The term is often used negatively, suggesting the displacement of poor communities by rich outsiders.' """, 'http://www.pbs.org/pov/flagwars/what-is-gentrification/'],
'racism': ["""'[Racism is] one’s benefiting from a system of privileges based on race that are subtly ingrained in the surrounding culture, making it difficult to detect. In this sense, all white people are racist; we benefit from this system of privileges.' """, 'https://bytheirstrangefruit.blogspot.com/2010/04/tatum.html'],
'accessibility': [""" 'Accessibility can be defined as the "ability to access" the functionality, and possible benefit, of some system or entity and is used to describe the degree to which a product such as a device, service, environment is accessible by as many people as possible.' """, 'https://www.disabled-world.com/disability/accessibility']

}